/*Action sur un évenement */
export default {
    ADD_FACET: "addFacet",
    ADD_IMPACT: "addImpact",
    ADD_LINKS: 'addLinks',
    CLONE_TREE:"cloneTree",
    CLONE_TRUNK: "cloneTrunk",
    CLONE_OPEN_TREE:"cloneOpenTree",
    CONFIGURE_LINK: "configureLink",
    CREATE_AND_OPEN_TREE: 'onCreateAndOpenTree',
    CREATE_ADD_RESSOURCE: 'createAddRessource',
    CREATE_FACET_ENTRY: 'onCreateFacetEntry',
    CREATE_IMPACT_ENTRY: 'onCreateImpactEntry',
    CREATE_TRUNK: 'onCreateTrunk',
    DELETE_FACETS: 'deleteFacets',
    DELETE_IMPACTS: 'deleteImpacts',
    DELETE_TREE: 'deleteTree',
    DELETE_LINK: 'deleteLink',
    EXCEPTION: 'exception',
    LOAD_FACETS: 'loadFacets',
    LOAD_IMPACTS: 'loadImpacts',
    LOAD_BRANCHES: 'loadBranches',
    LOAD_OPEN_TREE: 'loadOpenTree',
    LOAD_TRUNK: 'loadTrunk',
    LOAD_ROOTS: 'loadRoots',
    LOAD_TANK: 'loadTank',
    MOUNT_APP: 'mountApp',
    LOAD_OPEN_COMPARE_TO: 'loadOpenCompareTo',
    LOAD_TREE: 'loadTree',
    INVALIDATE_TRUNK: 'invalidateTrunk',
    RENAME_TRUNK: 'renameTrunk',
    SEARCH_TREE: 'searchTree',
    SEARCH_FACET_ENTRY: 'searchFacetEntry',
    SEARCH_IMPACT_ENTRY: 'searchImpactEntry',
    PUT_TRUNK_QUANTITY: "putTrunkQuantity"
};